from fastapi import APIRouter
from fastapi.responses import FileResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os

router = APIRouter(prefix="/api/report", tags=["Report"])

@router.get("/generate")
def generate_report():

    file_path = "farmer_report.pdf"

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 50

    c.setFont("Helvetica-Bold", 20)
    c.drawString(160, y, "Kerala Farmer AI Report")

    y -= 40
    c.setFont("Helvetica", 12)

    lines = [
        f"Generated Date: {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
        "",
        "Farmer Name: Akhil",
        "District: Kollam",
        "Crop: Rubber",
        "",
        "Today's Market Price: Rs.176/kg",
        "Estimated Yield: 320 kg",
        "",
        "AI Selling Advice:",
        "Sell now to cooperative buyers.",
        "",
        "Future Price Trend:",
        "Likely rise in next 3 days.",
        "",
        "Weather:",
        "Moderate rainfall expected.",
        "",
        "Generated by Kerala Farmer Smart Assistant"
    ]

    for line in lines:
        c.drawString(50, y, line)
        y -= 22

    c.save()

    return FileResponse(
        path=file_path,
        filename="Farmer_Report.pdf",
        media_type="application/pdf"
    )